services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5161:5161"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OpenAI__ApiKey=${OPENAI_API_KEY}
    restart: unless-stopped
