services:
  - type: web
    name: cv-analyzer-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: OpenAI__ApiKey
        sync: false
    healthCheckPath: /health
